services:
  app:
    image: package
    container_name: package_dev
    command: uvicorn package.server:app --host 0.0.0.0 --port 8000 --reload --reload-dir ./src
    ports:
      -  8000:8000
    volumes:
      - ./src:/app/src