[project]
name = "fiftyone-llm"
description = "An LLM-powered assistant for FiftyOne workflows"
authors = [{ name = "Afif Varikkodan", email = "afifv@metrized.com" }]
requires-python = ">=3.7"
dynamic = ["version", "readme"]
dependencies = ["click"]

[project.optional-dependencies]
dev = ["pip-tools", "black", "pytest", "pre-commit", "ruff"] # Developer tools

[tool.setuptools.dynamic]
version = { attr = "fiftyone-llm.__version__" }
readme = { file = ["README.md"] }


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
